# window
WINDOW_SIZE = (1536, 864)
WINDOW_TITLE = 'Chat Application'

# colors

''' MENU '''
MENU_BAR_COLOR = '#FFFFFF'
MENU_BAR_SHADE_COLOR = '#f2f2f2'

''' SCROLLBAR '''
SCROLLBAR_COLOR = '#E1E1E9'
SCROLLBAR_HOVER_COLOR = '#ECECF1'

''' SEARCH '''
SEARCH_COLOR = '#F5F5F5'
SEARCH_PLACEHOLDER_COLOR = '#A0AABA'

''' PLACEHOLDER '''
ENTRY_PLACEHOLDER_COLOR = '#A0AABA'

''' SIGN UP PAGE '''
SIGN_UP_BG_COLOR = '#5D83FF'
SIGN_UP_BUTTON_HOVER_COLOR = '#7EA1FF'

''' CHAT '''
OTHER_USERS_TEXT_BOUBBLE_COLOR = '#FFFFFF' # just a test
MAIN_USER_TEXT_BOUBBLE_COLOR = '#5D83FF'


MAIN_USER_CHAT_SIDE = 'right'
OTHER_USERS_CHAT_SIDE = 'left'


# icons
USER_ICON_SIZE = (32, 32)

SEARCH_ICON_SIZE = (12, 12)

# server commands
USER_INIT_COMMAND = 'USER_INIT'
USER_CHAT_COMMAND = 'USER_CHAT'
GLOBAL_CHAT_COMMAND = 'GLOBAL_CHAT'

# client commands
USER_INIT_REQUEST_COMMAND = 'USER_INIT_REQUEST'
NEW_USER_COMMAND = 'NEW_USER'
OTHER_USERS_COMMAND = 'OTHER_USERS'